---
apiVersion: v1
kind: Service
metadata:
  name: nsq-lookupd
spec:
  ports:  
  - name: tcp-port
    port: 4160
  - name: http-port
    port: 4161
  selector:
    app: nsq-lookupd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsq-lookupd
spec:
  selector:
    matchLabels:
      app: nsq-lookupd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nsq-lookupd
    spec:
      containers:
      - name: lookupd
        image: nsqio/nsq
        ports:
        - containerPort: 4160
          name: tcp-port
        - containerPort: 4161
          name: http-port
        command: ['/nsqlookupd']
        imagePullPolicy: Always
